### ISSUE TITLE
可以升级成带记忆的吗，只要运行程序就把之前记忆的程序最小化到托盘。

### ISSUE THREAD

**Issue by quchifanma** [tabris17/traymond#2]
每次都手动弄一次，好累啊，谢谢大神。

**Comment by tabris17** [comment]
这个“记忆”有个问题：“记住什么？”

记住窗口句柄？窗口句柄是动态分配的，会被重复使用，不能作为唯一识别ID。
记住进程的可执行文件路径？那万一进程开启了很多窗口，而用户只要隐藏其中一个呢？
一种可行的方案是按“窗口所属进程可执行文件+窗口Class Name+窗口标题”来作为唯一识别ID。但这种方案局限性比较大

**Comment by quchifanma** [comment]
受教啦大神，您说的很对，谢谢。

**Comment by tabris17** [comment]
另外还有个问题：如果程序设置为开机自动启动，Traymond启动时，需要隐藏的窗口还没创建怎么办？难道还要定时扫描一下么
其实我也有这个需求，但是还没想好怎么做

**Comment by quchifanma** [comment]
我们单位很多零碎的小软件，无最小化，功能单一。
本身的想法是对EXE整个缩放到托盘。


至于开机启动，简单BAT设置一个开机延迟启动即可

@ECHO OFF&setlocal enabledelayedexpansion
echo.

start /b "" "最小化.exe"

timeout /t 15 /nobreak 延迟15秒启动

start /b "" "其他程序.EXE"
start /b "" "其他程序2.EXE

exit


至于定时扫描就没必要啦， 对于其他需求执行原来的WIN+ALT+Z即可

**Comment by tabris17** [comment]
倒是可以做一个“Traymond运行后延迟XX秒隐藏下列（进程+标题）窗口”

**Comment by DynamicLoader** [comment]
一个想法，接受命令行参数，由trapmond启动程序并根据pid检索窗口句柄隐藏。不知道是否可行？

**Comment by tabris17** [comment]
> 一个想法，接受命令行参数，由trapmond启动程序并根据pid检索窗口句柄隐藏。不知道是否可行？

可行，不过Traymond的原始代码改动会比较大，不如重写一个。
另外当初之所以没使用这种方式是因为我要隐藏的是WSL下的Linux进程窗口，它的程序主进程和窗口所属进程不是同一个进程。
所以这种方式也有局限性

**Comment by tabris17** [comment]
v2.0 已实现
