### ISSUE TITLE
建议添加一键还原窗口快捷键

### ISSUE THREAD

**Issue by bingsunny0730** [tabris17/traymond#3]
目前的还原所有窗口功能只能通过托盘点击还原，不太方便，能否支持任意快捷热键的一键还原？

**Comment by tabris17** [comment]
这个功能不难。还是用户交互方式的问题。

第一种方式是为每个最小化窗口设置一个编号，比如0~9，每个编号对应一个热键，比如Win+Alt+F1~Win+Alt+F10。缺点是比较费全局热键，而且单手操作还挺困难的。

第二钟方式是用一个全局热键呼出最小化窗口列表，然后按下0~9数字键，选择要还原的窗口编号。缺点就是要按两下
