### ISSUE TITLE
显示热键被占用无法运行

### ISSUE THREAD

**Issue by westmood1219** [tabris17/traymond#4]
那个热键是win+shift+z吗？如果是的话我用spy++查过了，并没有被占用啊？

**Comment by tabris17** [comment]
会不会是程序已经启动了？你看看托盘里有没有。
另外发现了一个bug，不小心把热键注册的代码放到创建互斥量代码前面去了。
又另外，注册热键冲突的逻辑也有问题，热键注册失败应该让用户重新修改热键，而不是退出程序。
下版一并改了

**Comment by westmood1219** [comment]
确实已经在运行了，但托盘里没有显示

**Comment by westmood1219** [comment]
https://github.com/AlexanderPro/SmartSystemMenu，应该是和这个软件的2.7.1版本冲突了，我更新后两个程序就可以同时运行了

**Comment by tabris17** [comment]
v2.0 已修复
