### ISSUE TITLE
重启资源管理器会丢失托盘图标

### ISSUE THREAD

**Issue by Karanoyo** [tabris17/traymond#5]
#### 问题描述：

> 如果我现在隐藏了两个托盘图标，又刚好**百度网盘**自动升级（会自动***重启资源管理器***），就会**丢失**隐藏的托盘图标。
> 只能结束进程再重启才能恢复托盘图标。

*大佬 这个**难题**有解吗？😭*

**Comment by tabris17** [comment]
可以监控到资源管理器重启然后重新注册托盘图标。我琢磨一下怎么弄代价小一点
